// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfH-XYOmh_kBDm8oQm_IcGlDhom6Jr88',
    appId: '1:398727498716:android:d31fbbb3d68423f3fb5d19',
    messagingSenderId: '398727498716',
    projectId: 'petshelt-6339d',
    databaseURL: 'https://petshelt-6339d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petshelt-6339d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChkhT2rcM1U4fVuPTWtApzj0-HfFD0aJY',
    appId: '1:398727498716:ios:16e2e021ed12a44dfb5d19',
    messagingSenderId: '398727498716',
    projectId: 'petshelt-6339d',
    databaseURL: 'https://petshelt-6339d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petshelt-6339d.appspot.com',
    androidClientId: '398727498716-alu6fl03rtj2oe9f40m6mo6qjjppdbdg.apps.googleusercontent.com',
    iosClientId: '398727498716-1dl6l2omo47afa143rp0oak7gb9ih44c.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProjectt',
  );
}
